.TH bilidownloader-schedule 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-schedule - View the release schedule
.SH SYNOPSIS
.B bilidownloader schedule
[OPTIONS]
.SH DESCRIPTION
View the release schedule. Alias: calendar, cal, sch, timetable, tt
.SH OPTIONS
.SS "Output"
.TP
\fB--show-url, -u\fR
Generate URL to the show as well.
.SS "Filter"
.TP
\fB--day, -d\fR [today|now|monday|mon|mo|tuesday|tue|tu|wednesday|wed|we|thursday|thu|th|friday|fri|fr|saturday|sat|sa|sunday|sun|su]
Filter by a specific day.
.SH "SEE ALSO"
.BR bilidownloader (1)