.TH bilidownloader-history-list 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-history-list - Display the history of downloaded episodes
.SH SYNOPSIS
.B bilidownloader history list
[OPTIONS]
.SH DESCRIPTION
Display the history of downloaded episodes. Alias: ls, l
.SH OPTIONS
.TP
\fB--sort-by\fR [date|title|series-id|episode-id]
Sort by field (default: date).
.TP
\fB--history, --history-file, -h\fR PATH
Path to your history.txt file (default: /home/nattadasu/Bilibili/history.v2.tsv).
.SH "SEE ALSO"
.BR bilidownloader-history (1),
.BR bilidownloader (1)