.TH bilidownloader-history 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-history - View and manage history
.SH SYNOPSIS
.B bilidownloader history
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
View and manage history. Alias: his, h
.SH COMMANDS
.TP
\fBlist\fR
Display the history of downloaded episodes. Alias: ls, l
.TP
\fBquery\fR
Search history by series title, ID, or episode ID. Alias: q, search, find
.TP
\fBclear\fR
Clear history. Alias: clean, purge, cls, del, rm
.SH "SEE ALSO"
.BR bilidownloader (1)