.TH bilidownloader-watchlist-delete 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-watchlist-delete - Delete series from watchlist
.SH SYNOPSIS
.B bilidownloader watchlist delete
[OPTIONS] [SERIES]...
.SH DESCRIPTION
Delete series from watchlist. Alias: del, remove, rm
.SH ARGUMENTS
.TP
\fB[SERIES]...\fR
Provide the series URL or ID to be deleted in the watchlist. Use this option if you have the media/play URL of the show and want to bypass interactive mode.
.SH OPTIONS
.SS "Input"
.TP
\fB--assumeyes, -y\fR
Automatically answer yes for all questions.
.SS "Data Management"
.TP
\fB--watchlist, --watchlist-file, -w\fR PATH
Path to your watchlist.txt file (default: /home/nattadasu/Bilibili/watchlist.txt).
.TP
\fB--cookie, --cookie-file, -c\fR PATH
Path to your cookie.txt file. Use this argument option if you also want to update your Bilibili information.
.SH "SEE ALSO"
.BR bilidownloader-watchlist (1),
.BR bilidownloader (1)