.TH bilidownloader 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader - Assist you in ripping episode from BiliIntl
.SH SYNOPSIS
.B bilidownloader
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
Assist you in ripping episode from BiliIntl (Version: 3.0.5)
.SH OPTIONS
.TP
\fB--install-completion\fR
Install completion for the current shell.
.TP
\fB--show-completion\fR
Show completion for the current shell, to copy it or customize the installation.
.TP
\fB--help\fR
Show this message and exit.
.SH COMMANDS
.TP
\fBdownload\fR
Download via direct URL. Alias: down, dl, d
.TP
\fBtoday\fR
Get and download anime released today. Alias: now
.TP
\fBreleased\fR
Select and download anime released in the past 3 days. Alias: rel
.TP
\fBschedule\fR
View the release schedule. Alias: calendar, cal, sch, timetable, tt
.TP
\fBhistory\fR
View and manage history. Alias: his, h
.TP
\fBwatchlist\fR
View and manage watchlist. Alias: wl