.TH bilidownloader-watchlist 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-watchlist - View and manage watchlist
.SH SYNOPSIS
.B bilidownloader watchlist
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
View and manage watchlist, or download recently released episodes from watchlist. Alias: wl
.SH COMMANDS
.TP
\fBlist\fR
Read list of monitored series on Bilibili. Alias: ls, l
.TP
\fBadd\fR
Add a series to watchlist. Alias: insert, ins
.TP
\fBdelete\fR
Delete series from watchlist. Alias: del, remove, rm
.TP
\fBdownload\fR
Download all episodes from watchlist
.SH "SEE ALSO"
.BR bilidownloader (1)