.TH bilidownloader-watchlist-list 1 "November 2025" "bilidownloader 3.0.5" "User Commands"
.SH NAME
bilidownloader-watchlist-list - Read list of monitored series on Bilibili
.SH SYNOPSIS
.B bilidownloader watchlist list
[OPTIONS]
.SH DESCRIPTION
Read list of monitored series on Bilibili. Alias: ls, l
.SH OPTIONS
.SS "Output"
.TP
\fB--show-url, -u\fR
Generate URL to the show as well.
.SS "Data Management"
.TP
\fB--watchlist, --watchlist-file, -w\fR PATH
Path to your watchlist.txt file (default: /home/nattadasu/Bilibili/watchlist.txt).
.SH "SEE ALSO"
.BR bilidownloader-watchlist (1),
.BR bilidownloader (1)