---
# https://taskfile.dev
version: '3'

vars:
  APP_NAME: bilidownloader

tasks:
  remove-test:
    desc: Remove test installation of the package
    cmds:
      - pipx uninstall "{{.APP_NAME}}_test" -q
    preconditions:
      - sh: pipx list | grep -q "{{.APP_NAME}}_test"
        msg: "{{.APP_NAME}}_test is not installed"

  install-test:
    desc: Install the package for testing with pipx
    cmds:
      - pipx install --suffix "_test" ".[ass]"
    silent: true

  install:
    desc: Install the package locally with pipx
    cmds:
      - pipx install "."

  install-dev:
    desc: Install the package in development mode with all optional dependencies
    cmds:
      - pip install -e ".[ass]"

  uninstall:
    desc: Uninstall the package
    cmds:
      - pipx uninstall "{{.APP_NAME}}"
    preconditions:
      - sh: pipx list | grep -q "{{.APP_NAME}}"
        msg: "{{.APP_NAME}} is not installed"

  clean:
    desc: Clean build artifacts and cache
    cmds:
      - rm -rf build/
      - rm -rf dist/
      - rm -rf *.egg-info/
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete

  build:
    desc: Build the package
    cmds:
      - python -m build


  check:
    desc: Run all code quality checks
    deps: [lint-all, format-all]

  lint-all:
    desc: Run all linters
    cmds:
      - ruff check .
      - yamllint .
      - |
        for f in $(find . -name '*.toml'); do
          python -c "import tomllib; tomllib.load(open('$f', 'rb'))" || exit 1
        done
      - groff -Tascii -mandoc -Wall man/* | col -b > /dev/null
    preconditions:
      - sh: which ruff
        msg: "ruff must be installed (pip install ruff)"
      - sh: which yamllint
        msg: "yamllint must be installed (pip install yamllint)"

  format-all:
    desc: Format all files
    cmds:
      - ruff format .
      - ruff check --fix .
      - ruff check --select I --fix .

  run:
    desc: Run the application
    cmds:
      - python -m bilidownloader {{.CLI_ARGS}}

  test-run:
    desc: Run the test installation
    deps: [remove-test, install-test]
    cmds:
      - "{{.APP_NAME}}_test --help"

  deps:
    desc: Install or update development dependencies
    cmds:
      - pip install --upgrade build ruff pytest yamllint
